### ISSUE TITLE
fasttilemap cannt display tilemap correct!

### ISSUE THREAD

**Issue by jcy1001** [axmolengine/axmol#1306] opened 2023-08-25 01:01 UTC
- axmol version:latest
- windows
 
Steps to Reproduce:

1. produce a tilemap use tilededitor
2.use fasttilemap load and display
![8)X{OH1BN0Y 7MG53$B@DXT](https://github.com/axmolengine/axmol/assets/24226340/d2ef3f48-d843-4292-b447-5e106c6d0173)

![7)EY4{XB%Q4BEB6YLHDVKVW](https://github.com/axmolengine/axmol/assets/24226340/a0b87d0c-eb67-4236-b553-7b1477b00a76)

**Comment by jcy1001** [comment] 2023-08-25 01:02
i use tileeditor v1.10.2

**Comment by rh101** [comment] 2023-08-25 01:13
You've logged multiple issues related to FastTileMap, and in both you have provided very little information, and no test project, which makes it difficult to replicate the problem you're seeing.  So, in order for others to put time into helping you, please provide test projects for both this and issue #1300.

**Comment by jcy1001** [comment] 2023-08-26 09:08
i use this test tmx , one layer use 2 tileset image ,but  fasttilemap not support display correct 
[test.zip](https://github.com/axmolengine/axmol/files/12444953/test.zip)
![image](https://github.com/axmolengine/axmol/assets/24226340/807d5b83-5703-4ec0-9969-8cef527600e2)
demo use  cpp_tests

**Comment by jcy1001** [comment] 2023-08-26 14:08
![image](https://github.com/axmolengine/axmol/assets/24226340/e799cb6c-137a-48f4-9037-645558bd8bb3)

can support more than one tileset

**Comment by jcy1001** [comment] 2023-09-24 02:24
[dirt2longgrass_flat.zip](https://github.com/axmolengine/axmol/files/12707620/dirt2longgrass_flat.zip)
this is tmx file ,
this is test src ,just load tmx ,  it will occur, the tmx only one layer one tileset 
code add here ,in testcpp project
![](https://user-images.githubusercontent.com/24226340/263454528-807d5b83-5703-4ec0-9969-8cef527600e2.png)

**Comment by rh101** [comment] 2023-09-24 04:23
@jcy1001 To have a higher chance of solving issues, please always include the following:

- If it's a graphical issue, then show two images if possible, one of the expected output, and one of the actual output.
- If you're getting an error, then show the complete error log.

Other than that, is there something preventing you from using a debugger to step into the `FastTMXTileMap` code in order to track down the issue yourself?

**Comment by rh101** [comment] 2023-09-26 15:25
@jcy1001 The issue may be that you have gone over the tile limit.  Your tile map is 3500x3500 pixels, and given that each tile is 20 pixels, it amounts to 175x175 tiles = 30,625 tiles.  

The maximum number of tiles supported at the moment is 128 x 128 =16384. 

As long as you stay below the 16384 tile limit, then it will render correctly.  

To prove that it works, here is an example of 20x20 tiles (total 400 tiles):

Expected output:
![image](https://github.com/axmolengine/axmol/assets/8603230/4684d866-3899-411b-b2a2-ac0b0be683b4)

Actual output:
![image](https://github.com/axmolengine/axmol/assets/8603230/dc0b172b-7d6d-45e0-aea9-09440238fb56)

This is not a bug, just a limitation.  It's the same in Cocos2d-x.  If you do an online search for "Cocos2d-x TMX max map size" you'll see many posts about this.

**Comment by aismann** [comment] 2023-09-26 16:21
Should be on the Q&A Page

**Comment by rh101** [comment] 2023-09-27 00:48
Agree with aismann regarding adding this to Q&A page.  Also, this is a duplicate of issue #1300

**Comment by halx99** [comment] 2023-09-27 01:23
There macro config tmx use int32 for indices: 
- https://github.com/axmolengine/axmol/blob/dev/core/2d/FastTMXLayer.h#L369
- https://github.com/cocos2d/cocos2d-x/blob/v4/cocos/2d/CCFastTMXLayer.h#L339

**Comment by rh101** [comment] 2023-09-27 01:56
> There macro config tmx use int32 for indices:
> 
>     * https://github.com/axmolengine/axmol/blob/dev/core/2d/FastTMXLayer.h#L369
> 
>     * https://github.com/cocos2d/cocos2d-x/blob/v4/cocos/2d/CCFastTMXLayer.h#L339

~~I tried to enable it via cmake `add_definitions(-DAX_FAST_TILEMAP_32_BIT_INDICES)`, and it wouldn't work, which is strange given that the define exists in the VS2022 cpp_tests project, but still the code wouldn't recognize it.~~  Never-mind, it needs to be enabled within the Axmol engine/code.

Enabling it still doesn't entirely fix the issue, and the rendering output is still not correct:

Expected:
![image](https://github.com/axmolengine/axmol/assets/8603230/6a46a3ad-afd0-42ee-b986-c18f19408558)

Actual:
![image](https://github.com/axmolengine/axmol/assets/8603230/3d3a3829-d1fd-46d2-8492-0c6b1199cba8)

**Comment by jcy1001** [comment] 2023-09-27 01:58
@rh101  @halx99  thank u ,i follow u do that ,
#define  AX_FAST_TILEMAP_32_BIT_INDICES 1
when 250*250 tile(each tile 20pixel) is display ok,but  300*300 tile is still has that problem ,

**Comment by jcy1001** [comment] 2023-09-27 01:58
@rh101  @halx99  thank u ,i follow u do that ,
#define  AX_FAST_TILEMAP_32_BIT_INDICES 1
when 250*250 tile(each tile 20pixel) is display ok,but  300*300 tile is still has that problem ,

**Comment by jcy1001** [comment] 2023-09-27 01:59
@rh101  @halx99  thank u ,i follow u do that ,
#define  AX_FAST_TILEMAP_32_BIT_INDICES 1
when 250 * 250 tile(each tile 20pixel) is display ok,but  300 * 300 tile is still has that problem ,

**Comment by rh101** [comment] 2023-09-27 02:03
@jcy1001 There is still a limit, even with 32bit indices.

**Comment by halx99** [comment] 2023-09-27 02:39
> @rh101 @halx99 thank u ,i follow u do that , #define AX_FAST_TILEMAP_32_BIT_INDICES 1 when 250 * 250 tile(each tile 20pixel) is display ok,but 300 * 300 tile is still has that problem ,

try modify to unsigned short to int
https://github.com/axmolengine/axmol/blob/dev/core/2d/FastTMXLayer.cpp#L253

**Comment by halx99** [comment] 2023-09-27 03:12
modify line 253 to `auto quadIndex = static_cast<decltype(_indices)::value_type>(_tileToQuadIndex[tileIndex]);`

**Comment by halx99** [comment] 2023-09-27 03:26
> modify line 253 to `auto quadIndex = static_cast<decltype(_indices)::value_type>(_tileToQuadIndex[tileIndex]);`

works
![image](https://github.com/axmolengine/axmol/assets/6977319/4bdba9f2-d3ce-4d15-8da9-1e1999733290)

**Closed as completed** 2023-09-27 03:38 UTC
Labels: bug

**Comment by halx99** [comment] 2023-09-27 03:40
Fixed, @jcy1001 thanks for your report, @rh101 thanks for your analyzes and test.
