### ISSUE TITLE
TabControl

### ISSUE THREAD

**Issue by Arvant** [axmolengine/axmol#1221] opened 2023-05-30 14:51 UTC
- axmol version:1.0
- devices test on: win32,android
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - Visual Studio: 
      - VS version: 2022 (17.4)
      - MSVC version: 1929, 1934
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

when I create a layer and add Tabcontrol to it. if set the layout listener setswallow to true and return true in touch began. the tab bar not work. but if  add button to this layout the button work.

`
auto listener = EventListenerTouchOneByOne::create();
    listener->setSwallowTouches(true);

    listener->onTouchBegan = [](Touch* t, Event* e) {
        return true;
    };
    listener->onTouchMoved = [](Touch* t, Event* e) {
    };
    listener->onTouchEnded = [](Touch* t, Event* e) {
    };

    auto layerColorPopup = ax::LayerColor::create(Color4B(0, 0, 0, 190));

    this->addChild(layerColorPopup);
    _eventDispatcher->addEventListenerWithSceneGraphPriority(listener, layerColorPopup);

     auto layerColorPopup = ax::LayerColor::create(Color4B(0, 0, 0, 190));
 
    this->addChild(layerColorPopup);
    _eventDispatcher->addEventListenerWithSceneGraphPriority(listener, layerColorPopup);

    auto bg_tab_continers = Sprite::create("equipment/brown.png");
    bg_tab_continers->setAnchorPoint(Vec2::ANCHOR_MIDDLE_BOTTOM);
    bg_tab_continers->setPosition(Vec2(200, 0));

    auto sp_header_tab = Sprite::create("equipment/tabs.png");

    auto tab = ax::ui::TabControl::create();
    tab->setGlobalZOrder(44444);
    tab->setAnchorPoint(Vec2::ANCHOR_BOTTOM_LEFT);
    tab->setPosition(Vec2(5, 10));
    tab->setHeaderHeight(sp_header_tab->getContentSize().height);
    tab->setHeaderWidth((bg_tab_continers->getContentSize().width / 3));
    tab->setHeaderDockPlace(ax::ui::TabControl::Dock::TOP);
    tab->setHeaderSelectedZoom(0.0f);

    auto button = ax::ui::Button::create("equipment/tabs.png");

    button->setTitleText("Button Text");
    button->addTouchEventListener([&](Ref* sender, ax::ui::Widget::TouchEventType type) {
        switch (type)
        {
        case ui::Widget::TouchEventType::BEGAN:
            break;
        case ui::Widget::TouchEventType::ENDED:
            AXLOG("test");
            break;
        default:
            break;
        }
        });
    button->setPosition(layerColorPopup->getContentSize() / 2);
    layerColorPopup->addChild(button);

    auto header1 = ax::ui::TabHeader::create("head", "equipment/tabs.png", "equipment/tabs_select.png");

    header1->setTouchEnabled(false);
    header1->setTouchEnabled(true);
    header1->addTouchEventListener([&](Ref* sender, ax::ui::Widget::TouchEventType type) {
        switch (type)
        {
        case ui::Widget::TouchEventType::BEGAN:
            break;
        case ui::Widget::TouchEventType::ENDED:
            AXLOG("Touch");
            break;
        default:
            break;
        }
        });

    header1->setZoomScale(0.0f);

    auto container1 = ax::ui::Layout::create();
    container1->setContentSize(bg_tab_continers->getContentSize());
    /////////-------------------------------------------------- container1 atechment

    tab->insertTab(0, header1, container1);
    //tab->insertTab(2, header3, container3);

    tab->setSelectTab(0);
    this->addChild(tab);

`

**Comment by aismann** [comment] 2023-05-30 16:21
@Arvant 
have you seen the cpp-test example?
Maybe you can comparing your implementation with this one first?

**Comment by Arvant** [comment] 2023-05-30 16:27
> @Arvant have you seen the cpp-test example? Maybe you can comparing your implementation with this one first?

yes i see it. But this problem has been there for a long time in cocos2d

**Comment by Arvant** [comment] 2023-05-31 14:41
> > yes i see it. But this problem has been there for a long time in cocos2d
> 
> ? What are you mean? Have you a link to this cocos2d issue too? Is the cpp-test example not working/usable for your example/situation?

i early in cocos2d-x have this problem and I create custom tab for solve this. now i test above code in axmol and see the problem is exist too. this case not use in test project and you need to create simple project and insert my code in project.

**Comment by Arvant** [comment] 2023-06-03 07:11
> > this case not use in test project and you need to create simple project and insert my code in project.
> 
> > Sprite::create("equipment/brown.png");
> 
> @Arvant can you provide a working example?);

yes I upload test.

**Comment by aismann** [comment] 2023-06-03 19:49
Remove this line:
`_eventDispatcher->addEventListenerWithSceneGraphPriority(listener, layerColorPopup);`

**Comment by Arvant** [comment] 2023-06-04 05:50
> Remove this line: `_eventDispatcher->addEventListenerWithSceneGraphPriority(listener, layerColorPopup);`

if you went to create popup you need this listener to  Swallow touches.

**Comment by aismann** [comment] 2023-06-04 07:21
Sorry I'm out.
Your example works now. 
Thats was the challenge.

**Comment by aismann** [comment] 2023-06-04 07:37
@Arvant 
Please close this issue.
Thanks

**Comment by rh101** [comment] 2023-06-04 07:39
If you're creating a popup with the tab control on it, then this line:

`this->addChild(tab);` 

should be this: 

`layerColorPopup->addChild(tab);` 

This wouldn't be causing your issue though, since the touch event is hitting the layerColorPopup before it gets to the tab control, which is actually strange.

**Comment by rh101** [comment] 2023-06-04 07:40
> @Arvant
> Please close this issue.
> Thanks

The problem isn't solved, as there does seem to be some issue with how the touches are being handled.

**Comment by aismann** [comment] 2023-06-04 07:50
Please provide an example.

**Comment by rh101** [comment] 2023-06-04 08:00
> Please provide an example.
> And please compare the cpp-test example with your implementation too.

The code provided by the OP, while a little messy and harder to follow, is actually the correct example.

This is the structure:

Scene
  |-- PopupLayer
         |--TabControl
               |-- TabHeader1
               |-- TabHeader2 
               |-- TabHeaderN... etc

The problem seems to be that the touch input is being received by the Scene, then PopupLayer, then TabControl (Widget), then TabHeader (Widget), at least from what I can see in the output.  From my understanding, the highest layers should be getting input before the lower layers, but that isn't what seems to be happening here.

**Comment by rh101** [comment] 2023-06-04 09:03
When a touch event occurs, the method `EventDispatcher::sortEventListenersOfSceneGraphPriority()` is eventually called to sort the event listeners.  In here is where the problem first appears.  The UIButton is first in the list, then the `layerColorPopup`, then the `HelloWorld` scene, then any tab control header widgets.   This causes the button touch handler to be called first, then the layerColor, then the scene, and finally the tab header widgets.  

The widgets should be higher up in priority, and ahead of the `layerColorPopup`, but they are not.  I am not sure why this is happening as of yet, and unfortunately I don't have any more time at the moment to look into it.

@Arvant Note, get rid of `tab->setGlobalZOrder(44444);` from the example you provided, because that is not required, and just adds more confusion to the issue.

**Comment by rh101** [comment] 2023-06-04 12:14
@Arvant There is a work-around for this, but you would need to be aware of a few things.

Scene is at global Z of 0
Popup layer is at a global Z of 100 (arbitrary value, as long as it's greater than the scene global Z value).

When you create the popup, also create another layer (let's call it TouchBlockLayer) and give it a global Z of less than the popup layer (even 0), and add a touch event listener to it.  Then, add this layer to the scene.  

What happens now is that your popup will work as intended, but no touch events will propagate through the TouchBlockLayer to the scene below it.

So it will be like this:

```
Scene (globalZ = 0)
  |-- TouchBlockLayer (globalZ = 0 to 99.9999 etc)
  |-- PopupLayer (globalZ = 100)
         |--Popup child (like tab control etc) (globalZ = 100)
```

What you need to look out for is that *all* children of the popup layer must be at the same or greater global Z values than the popup.  It's best to just make them all the same as the popup global Z unless you have a specific reason not to.  

This will work, as this is actually the method I use to achieve something like what you're trying to do.  When you remove the popup, also remove the TouchBlockLayer.

**Comment by Arvant** [comment] 2023-06-04 12:27
> @Arvant There is a work-around for this, but you would need to be aware of a few things.
> 
> Let's say you create the following: Scene is at global Z of 0. Popup layer is at a global Z of 100 (arbitrary value, as long as it's greater than the scene global Z value).
> 
> When you create the popup, also create another layer (let's call it TouchBlockLayer) and give it a global Z of less than the popup layer (even 0), and add a touch event listener to it. Then, add this layer to the scene.
> 
> What happens now is that your popup will work as intended, but no touch events will propagate through the TouchBlockLayer to the scene below it.
> 
> So it will be like this:
> 
> ```
> Scene (globalZ = 0)
>   |-- TouchBlockLayer (globalZ = 0 to 99.9999 etc)
>   |-- PopupLayer (globalZ = 100)
>          |--Popup child (like tab control etc) (globalZ = 100)
> ```
> 
> What you need to look out for is that _all_ children of the popup layer must be at the same or greater global Z values than the popup. It's best to just make them all the same as the popup global Z unless you have a specific reason not to.
> 
> This will work, as this is actually the method I use to achieve something like what you're trying to do. When you remove the popup, also remove the TouchBlockLayer.

[rh101](https://github.com/rh101) I test this way before but it not work for me. I have forced to use layer and button to simulate tab control in popups. I have this problem in cocos2d-x 4 too. I debug cocos2d-x touch listener like you and see that it have problem in touch priority. I work with global Z order and fixed touch priority too but not work that.

**Comment by rh101** [comment] 2023-06-04 12:56
@Arvant The method I described with global Z does in fact work, since I've been using it for years, but, it may not be ideal, since it requires tracking the global Z etc.

I think I've found a more reliable solution to this issue, and it seems to be working.  A PR will be up soon.  Even if the PR is not merged in, you can just merge in the changes with your own copy of the engine code.  The changes are trivial.

**Comment by rh101** [comment] 2023-06-04 13:20
@Arvant The PR is up. Merge it in to your own code to check if it works.

**Comment by rh101** [comment] 2023-06-04 14:46
@Arvant The PR was simplified, as it is better to keep the functionality contained in EventDispatcher rather than add unnecessary functionality to Node and ProtectedNode.

**Comment by aismann** [comment] 2023-06-04 16:47
@rh101 
Thanks for this PR.

**Comment by Arvant** [comment] 2023-06-05 05:45
@rh101 it work perfect. Thanks for this PR.

**Comment by rh101** [comment] 2023-06-05 09:22
@Arvant Please close this issue since the PR with the fix has been merged into the dev branch.

**Closed** 2023-06-05 12:10 UTC
