### ISSUE TITLE
Draw Polygon wrong

### ISSUE THREAD

**Issue by NgVThangBz** [axmolengine/axmol#1319] opened 2023-09-08 04:12 UTC
Currently DrawNode->drawPolygon is using the wrong triangulation method (from cocos2dx), which leads to complex and concave polylines being drawn incorrectly.

why not replace the more accurate triangulation with triangulation algorithms (poly2tri...??)

cocos2dx v3 now has a new update to draw polygon more accurately (not released yet), i haven't tried it but maybe it will work, or use poly2tri to be able to triangulate correctly than

**Comment by rh101** [comment] 2023-09-08 05:12
> Currently DrawNode->drawPolygon is using the wrong triangulation method (from cocos2dx), which leads to complex and concave polylines being drawn incorrectly.

Do you have an example, and by that I mean screenshots of incorrect and correct rendering?

> cocos2dx v3 now has a new update to draw polygon more accurately (not released yet), i haven't tried it but maybe it will work, or use poly2tri to be able to triangulate correctly than

There are no new versions of Cocos2d-x v3, and unlikely for any others to be released given that the Cocos team haven't worked on it for over 2 years.  So, what exactly do you mean by that statement?

**Comment by NgVThangBz** [comment] 2023-09-08 06:42
- You can see the image below: the blue color uses poly2tri for triangulation, and the red color uses the default version.
![image_2023-09-08_13-36-42](https://github.com/axmolengine/axmol/assets/125545428/71b60e4b-fc00-409c-bd61-99732e02499d)

- I'm not talking about released versions, I'm talking about DrawNode code on the contributed v3 branch,

**Comment by NgVThangBz** [comment] 2023-09-08 07:08
I just tested cocos2dx v3, and they work wrong, don't worry about them, sorry

**Comment by rh101** [comment] 2023-09-08 07:13
> I just tested cocos2dx v3, and they work wrong, don't worry about them, sorry

Sorry, that's what I actually meant. There were no new PRs or updates listed against cocos2d-x v3 with polygon related code, so I wasn't sure what you were referring to.

Anyhow, I'm pretty sure poly2tri was updated a while back by @aismann, so perhaps he may be able to give his input regarding this.

**Comment by aismann** [comment] 2023-09-08 14:27
> * You can see the image below: the blue color uses poly2tri for triangulation, and the red color uses the default version.
>   ![image_2023-09-08_13-36-42](https://user-images.githubusercontent.com/125545428/266524188-71b60e4b-fc00-409c-bd61-99732e02499d.png)
> * I'm not talking about released versions, I'm talking about DrawNode code on the contributed v3 branch,

@NgVThangBz 
Your vertices list from this example plz.
And yes its known (see cpp-tests DrawNode tests)
=> cocos2dx 4.0 issue (implementation)

**Comment by NgVThangBz** [comment] 2023-09-11 01:33
[0] = {x=290.250000 y=98.1250000 }
[1] = {x=235.000000 y=90.8750000 }
[2] = {x=270.500000 y=109.875000 }
[3] = {x=235.000000 y=119.125000 }
[4] = {x=275.250000 y=145.875000 }
[5] = {x=249.500000 y=145.875000 }
[6] = {x=249.500000 y=178.125000 }
[7] = {x=275.250000 y=187.375015 }
[8] = {x=294.750488 y=168.333344 }
[9] = {x=311.250000 y=181.125000 }
[10] = {x=257.000000 y=213.625015 }
[11] = {x=338.500000 y=193.125000 }
[12] = {x=300.000000 y=211.125015 }
[13] = {x=333.750000 y=211.125015 }
[14] = {x=368.250000 y=206.625000 }
[15] = {x=377.000000 y=178.125000 }
[16] = {x=421.750000 y=170.125000 }
[17] = {x=416.250000 y=115.375000 }
[18] = {x=391.250000 y=157.875000 }
[19] = {x=338.500000 y=131.625000 }
[20] = {x=362.750000 y=131.625000 }
[21] = {x=362.750000 y=106.875000 }
[22] = {x=306.500000 y=119.125000 }
[23] = {x=324.250000 y=85.1250000 }
[24] = {x=227.500000 y=61.8750000 }
![image_2023-09-11_08-19-32](https://github.com/axmolengine/axmol/assets/125545428/76a2de36-62e6-42fe-b7a6-a3f7dc64493d)
im create new polygon, please check

**Comment by aismann** [comment] 2023-09-11 09:35
@NgVThangBz 
Thats issue comes with Cocos2dx 4.0.

**Comment by NgVThangBz** [comment] 2023-09-11 09:40
yes it happens with both 3.17 and 4.0 and it leads to axmol also crashing, so let's find a solution, currently I'm using poly2tri to solve the problem.

**Comment by aismann** [comment] 2023-09-12 04:56
It happens only  with filled polygon:
see here:
DrawNode::draw*Poly*: SolidPoly/Polygon cannot render concave structure correct. #829
The changed draw order is not a solution for complex concave polygons.

Thats the reason for wrong filled polygons (using GL_TRIANGLE_FAN):
(screenshot from [ here:](https://stackoverflow.com/questions/66776865/draw-concave-shapes-with-gl-polygon))
![image](https://github.com/axmolengine/axmol/assets/8652787/f3e74d6a-0526-4dbc-94e5-14862b93e1e6)

Here a possible solution (pseudo code):
```
if isConvex
    use the Cocos2dx version
else
   create triangles and fill each
```
Another idea is to use the class AutoPolygon/PolygonInfo class to create the triangles

The problem is on each solution is it filled only (no border line) 
=> workaround: drawPoly for the border)

**Comment by aismann** [comment] 2023-09-12 06:33
@halx99 you can also add tags like on #829

**Comment by aismann** [comment] 2023-09-12 07:36
> yes it happens with both 3.17 and 4.0 and it leads to axmol also crashing, so let's find a solution, currently I'm using poly2tri to solve the problem.

@NgVThangBz 
Do you have a PR?

**Comment by NgVThangBz** [comment] 2023-09-12 07:40
I simply used poly2tri to create the triangles, and colored them @aismann

**Comment by iAndyHD3** [comment] 2023-09-12 14:16
do we have an axmol test where this issue can be seen? if not please add

**Comment by aismann** [comment] 2023-09-12 22:09
> I simply used poly2tri to create the triangles, and colored them 

@NgVThangBz 
You used an app like paint, right?
Polztri makes only the triangles like autopolygon or get you a filled Polygon with polyti directly

**Comment by aismann** [comment] 2023-09-13 07:08
> do we have an axmol test where this issue can be seen? if not please add

we have:
![image](https://github.com/axmolengine/axmol/assets/8652787/425faa64-16c9-4643-8474-cc27b5ea2179)

and an info too:
![image](https://github.com/axmolengine/axmol/assets/8652787/7832dce6-5149-4006-83e4-77fcc499c6a6)

**Comment by NgVThangBz** [comment] 2023-09-13 07:39
yes, instead of using <polyline>, I use poly2tri and triangulate them, what's left is just to color each triangle,
This solves my problem, however I still think a modification of the drawPolygon method is needed
![image_2023-09-13_08-07-31](https://github.com/axmolengine/axmol/assets/125545428/d1c5b336-e054-42d0-aa47-71ac3945f81d)

**Comment by aismann** [comment] 2023-09-13 09:19
@NgVThangBz 
What is `globalToDrawing(pt) `doing (code snippet)?

**Comment by NgVThangBz** [comment] 2023-09-13 09:21
@aismann 
it's just for frame conversion, you can ignore it

**Comment by aismann** [comment] 2023-09-14 10:40
Ok I have a solution:
Coming PR needs some more tests datas, @NgVThangBz maybe you have some more?
Format:
```
Vec2 vertices[] = { 
   {290.250000, 98.1250000 },
    {235.000000, 90.8750000 },
...
    {324.250000, 85.1250000 },
    {227.500000, 61.8750000 } };
```

![image](https://github.com/axmolengine/axmol/assets/8652787/3706a323-8f68-4121-a532-31e78914f35d)

**Comment by aismann** [comment] 2023-09-14 16:03
@halx99 you can remove the "help wanted".

**Comment by NgVThangBz** [comment] 2023-09-15 01:42
I have created 2 more data (files below), in the file there are 2 Vec2 lists:
-data1 is manually generated,

![image_2023-09-15_08-36-15](https://github.com/axmolengine/axmol/assets/125545428/c349a1ac-1204-49de-9d6b-aaaed4afbd8c)

-data2 is taken from a <path> in the svg file I read, (very complicated),I think it can be later
![photo_2023-09-15_08-40-03](https://github.com/axmolengine/axmol/assets/125545428/965e3480-df21-49c6-ae48-b05103b231d3)

data here:
[polyLineData.txt](https://github.com/axmolengine/axmol/files/12614778/polyLineData.txt)

**Comment by aismann** [comment] 2023-09-15 04:28
Looks good (but there are some issues which i have to fix/changes before I can make the PR):
![image](https://github.com/axmolengine/axmol/assets/8652787/01268b65-d41c-47b4-9566-279635f7ed2c)

**Comment by aismann** [comment] 2023-09-19 09:42
I think I need some more time (not all is working at this moment)!
@halx99 please add 'long story', 'enhancement'  tag
However I will add some more 'new' drawing methodes too:
eg: drawPolyline with thickness 
![image](https://github.com/axmolengine/axmol/assets/8652787/278a34c2-fe4c-4172-bd3d-1107853728f9)

**Comment by aismann** [comment] 2023-09-19 12:17
Here a preview of the `drawPolyline with thickness`
![image](https://github.com/axmolengine/axmol/assets/8652787/54fb8f03-46cd-44c1-a38f-922a63fa8bf7)

**Comment by aismann** [comment] 2023-10-09 13:27
I opening an issue on poly2tri
https://github.com/jhasse/poly2tri/issues/54

![image](https://github.com/axmolengine/axmol/assets/8652787/596f1f54-6ed4-4fd6-85b6-125f6579ddf7)

@NgVThangBz 
Maybe you want check your data also for correctness?

Thats the poly2tri result (axmol has the same of course):
![image](https://github.com/axmolengine/axmol/assets/8652787/670defd8-37c0-4640-bf3d-1f78ba37a902)

**Comment by NgVThangBz** [comment] 2023-10-10 01:14
@aismann maye my data wrong, you can check again with data:
[polyLineData.txt](https://github.com/axmolengine/axmol/files/12851709/polyLineData.txt)
but i think axmol like poly2tri is fine

**Comment by aismann** [comment] 2023-10-10 05:14
@NgVThangBz 
I got an exeption with your new data on p2t.exe (poly2tri testbed)
Please check it with poly2tri first.
![image](https://github.com/axmolengine/axmol/assets/8652787/fef5775d-8db5-4c5e-bf71-7b1b57741f54)

**Comment by aismann** [comment] 2023-10-25 07:47
@halx99 
Short info: I will have no time to work on it this year.

**Comment by aismann** [comment] 2023-11-06 21:52
Small update (seems it works now correct)
![image](https://github.com/axmolengine/axmol/assets/8652787/c2225760-4a21-477f-9bf6-b321d9f97af4)

**Comment by aismann** [comment] 2023-11-16 05:30
@NgVThangBz 
can be closed now.

**Comment by NgVThangBz** [comment] 2023-11-16 06:04
@aismann  yes, thank you, it good

**Comment by aismann** [comment] 2023-11-16 15:05
> @aismann yes, thank you, it good

@NgVThangBz 
You are the author, you can close it (im not) ;)

**Closed as completed** 2023-11-17 01:04 UTC
Labels: enhancement, cocos2dx, long term
