### ISSUE TITLE
Micro Hangs:  iOS Micro Hang Issue After Development Branch Update

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#2196] opened 2024-10-01 14:12 UTC
Hi,
We recently updated our development branch (which hadn’t been done in a while) and performed regression testing to ensure everything was functioning correctly. However, on the iPhone version of the app, we observed some micro hangs during screen transitions, with delays of around 308ms. These micro hangs are noticeable and affect the user experience. After testing on Android, everything appears to work as expected, so it seems that only iPhone and iPad devices are impacted.
We instrumented the app with Time Profiler and identified that the function `node::switchTo(int n) `might be the one contributing to these delays (micro hangs). Could anyone confirm if there have been any recent changes in this area that might be affecting the iOS platform specifically?

For context:
	•	The class responsible for view switching inherits from ax::LayerMultiplex. LayerMultiplex is a convenient class used for switching between multiple layers easily.
	•	We are calling the switchTo method during these transitions.

To better illustrate the issue, I have attached two videos:
	1	Before the update: fastTransitions.MP4
	2	After the update: slowTransitions.MP4 – In this video, I attempt to go as fast as possible, but you can observe the micro hangs.
	
Additionally, I’ve included a screenshot of the Time Profiler for further reference.
Given that there have been multiple updates on the development branch, we suspect the issue might be tied to a change in how view switching is handled on iOS, but we are not entirely sure.
Thank you in advance for your assistance.

Before the update:

https://github.com/user-attachments/assets/02dd5a44-c321-4d0a-a5cd-3ca019859aed

After the update:

https://github.com/user-attachments/assets/f610a8c5-7497-45e2-9cac-e2794f3221a6

The profiler data:

![image](https://github.com/user-attachments/assets/8f62bb7a-dc7b-4959-b843-9b4adfede45a)

- axmol version: Development branch ( 6 days ago)
- devices test on: iP11, iPhone 14, iPad Pro 11inch, Redmi Note9, Alcatel
- developing environments
   - NDK version: r23c
   - Xcode version: 15.4
   - Visual Studio: 
      - VS version: n/a
      - MSVC version: n/a
      - Windows SDK version: n/a
   - cmake version: 3.30.1

Steps to Reproduce:

1. Create Layers using Axmol LayerMultiplex
2. Switch between them

**Comment by rh101** [comment] 2024-10-01 14:26
1. Have you created a minimal test project to see if you can reproduce this outside of your main application?  If you have not, then please do so, and link the project in a post.
2. Can you please use Xcode Instruments to profile the application during the use of the `ax::LayerMultiplex::switchTo`?  It should allow you to drill down directly to where the issue is.

**Comment by asnagni** [comment] 2024-10-01 15:13
Hi rh101,
   I think we are all professionals here and we know how to work.
    My question was about if any of you would know if anyone did some work that could cause this issue since lot of changes happened. That would help to know if someone worked in that area before starting to build huge use cases and spinning around. We should start with the basics.
   
Thank you and I do appreciate your help,
Stay safe

**Comment by asnagni** [comment] 2024-10-01 15:17
Also, like I said, the fact that it is not happening on Android it's clear that the update is causing this issue, not the code that we have. That is why I was asking that question.
  The code used on Android and iOS is the same.

Thank you,
Stay safe

**Comment by smilediver** [comment] 2024-10-01 15:28
Profile with Xcode Instruments and see/post what is taking so long, otherwise it's just a guess game.

**Comment by rh101** [comment] 2024-10-01 15:29
> Hi rh101, I think we are all professional here and we know how to work. 

I don't understand the reason for that remark.  I was being direct in asking for the most basic information that should be included in any issue posted against any project, such as code samples, a reproducible test case, etc...  The reason for this is that it verifies something important, being that the issue is in fact caused by something in the engine, and not an oversight in the application using the engine.

Also, with regards to the CPU profiling, for issues like this, it is extremely important to provide this kind of information.

> My question was about if any of you would know if anyone did some work that could cause this issue since lot of changes happened. That would help to know if someone worked in that area before starting to build huge use cases and spinning around. We should start with the basics.

The problem with asking that kind of question is that the engine has had a lot of changes, so attempting to remember what changes were done is unlikely to yield an answer (unless you're lucky).  You can always look through the commit history, and use the git "blame" command to see specifically when and what changes were made, which may point you to the reason for the issue.

> Also, like I said, the fact that it is not happening on Android it's clear that the update is causing this issue, not the code that we have. That is why I was asking that question.
> The code used on Android and iOS is the same.

I understand, but do not rely on this reasoning.  Just because it's not obvious on Android does not mean it is not happening on Android.  The only way to verify this is to use the CPU profiling tools on both platforms and compare.

**Comment by asnagni** [comment] 2024-10-01 15:38
Hi rh101,
  Sorry for my comments, it's just a bit frustrating to see things braking, when you try to align with the latest code to take advantage of all the good things that were done.
  It is just illustrating that the regression tests were not done properly. This is something that Axmol can improve one. Any suggestions? I'm willing to help in anyway to avoid these situations.
  
 I will provide a test app (This is not an issue and you are right).
  
  Thank you,
  Stay safe

**Comment by asnagni** [comment] 2024-10-01 15:39
> Profile with Xcode Instruments and see/post what is taking so long, otherwise it's just a guess game.

Yes you are right . Please see my latest comment.

**Comment by rh101** [comment] 2024-10-01 15:51
> It is just illustrating that the regression tests were not done properly. This is something that Axmol can improve one. Any suggestions? I'm willing to help in anyway to avoid these situations.

By any chance, have you run `cpp-tests`, test `34:Node: Menu`, to see if it happens there? That test uses `LayerMultiplex`.

Also, from a quick look at the functionality `LayerMultiplex` provides, while seemingly simple, its usage needs to be carefully considered, because it can cause excessive memory usage and performance issues on switches, depending on how many nodes are in the list, and the content of those nodes.

**Comment by asnagni** [comment] 2024-10-01 23:14
Hi rh101,
    No, I didn't but that's a good idea. I will perform some tests and observe the performance.
  I will share the tests performed and the results.
 
  
  Thank you for suggesting this idea, I do appreciate.
  Stay safe.

**Comment by rh101** [comment] 2024-10-02 07:08
> It is just illustrating that the regression tests were not done properly. This is something that Axmol can improve one. 

This is an open source project with no dedicated QA, and while as much care as possible is taken to review and test changes, there needs to be a more reasonable level of expectation on how well this process goes.  Also, the `dev` branch is unreleased, and constantly changing, with no guarantees being made on its production worthiness. 

> Any suggestions? I'm willing to help in anyway to avoid these situations.

You are already helping, as you have discovered a possible issue, and have reported it, but what would help a lot more is by going one step further, being to actually dig into the issue in more detail on your end, such as the aforementioned CPU profiling.  Diagnosing the problem at the source (excuse the pun) can prove to be more valuable than having others attempt to reproduce it on their end.  In addition to that, it's likely to bring about a quicker resolution to the issue.

The contributors associated with this project put their own effort and time into this, and as far as I'm aware, it's unpaid, so we cannot expect people to instantly jump onto each and every issue that pops up.  Issues that are addressed quickly are usually ones that have a wide impact, are in an area that contributors are very familiar with, or contain sufficient information to be able to quickly reproduce the issue with minimal time and effort.

So, anyone wishing to help would do so by providing their own time and effort to move this project forward.

**Comment by asnagni** [comment] 2024-10-02 10:39
Hi rh101,
I believe there might have been a misunderstanding, so I’d like to clarify my thoughts:

	1. I fully understand that Axmol is an open-source project, and I share the same passion for its success as everyone involved. My intention was not to suggest that anyone is doing something wrong but to explore how we can leverage industry best practices to strengthen the project. Incorporating proven processes like regression testing, among others, could help enhance the overall quality. I see this as an opportunity for us, as a passionate community, to discuss and collaborate on how we can implement such practices to benefit Axmol even more.
	
	2. Regarding the issue we encountered, we initially downloaded the release version (2.1.5) and noticed the problem. To ensure it wasn’t already resolved, we then checked the development branch, as it’s common for fixes to be made there post-release. However, you’re right that it would have been more appropriate to report the issue specifically in the release version. I will certainly do so moving forward.
	
	3. I want to reiterate that I deeply appreciate the effort and dedication the contributors put into this project. If my earlier message implied otherwise, I apologize—that was not my intention. The work being done here is fantastic.
In the end, my goal is to have an open dialogue about how we can improve Axmol by potentially incorporating some software development standards from the industry. I hope this is a discussion you would be open to having as we work together to continue making Axmol a great project.

Thank you, and take care!
Stay safe

**Comment by asnagni** [comment] 2024-10-02 10:42
Hi rh101,
I believe there might have been a misunderstanding, so I’d like to clarify my thoughts:

1.  I fully understand that Axmol is an open-source project, and I share the same passion for its success as everyone involved. My intention was not to suggest that anyone is doing something wrong but to explore how we can leverage industry best practices to strengthen the project. Incorporating proven processes like regression testing, among others, could help enhance the overall quality. I see this as an opportunity for us, as a passionate community, to discuss and collaborate on how we can implement such practices to benefit Axmol even more.
	
2. Regarding the issue we encountered, we initially downloaded the release version (2.1.5) and noticed the problem. To ensure it wasn’t already resolved, we then checked the development branch, as it’s common for fixes to be made there post-release. However, you’re right that it would have been more appropriate to report the issue specifically in the release version. I will certainly do so moving forward.
	
3. I want to reiterate that I deeply appreciate the effort and dedication the contributors put into this project. If my earlier message implied otherwise, I apologize—that was not my intention. The work being done here is fantastic.
In the end, my goal is to have an open dialogue about how we can improve Axmol by potentially incorporating some software development standards from the industry. I hope this is a discussion you would be open to having as we work together to continue making Axmol a great project.


Thank you, and take care!
Stay safe

**Comment by asnagni** [comment] 2024-10-02 10:53
I can also provide some equipment to help (iPhone & iPad).

**Comment by rh101** [comment] 2024-10-02 11:05
The only way I can imagine testing would work is if was completely automated, otherwise it requires a significant amount of time and effort to accomplish manually.  This won't solve anything though, since the issue with automated testing is that it can only work with what can be automated, which may only be a small subset of the engine functionality.  

At the moment, I don't see any easy solution to the topic of testing, but hopefully someone else can, and this is perhaps better left to a separate discussion.  For now, it is best we focus on the issue mentioned in your initial post.  Have you managed to get anywhere with the CPU profiling?

**Comment by halx99** [comment] 2024-10-02 11:50
This issue is regression introduced by 2.1.5, and 2.1.4 works fine, right?

**Comment by asnagni** [comment] 2024-10-02 12:08
> The only way I can imagine testing would work is if was completely automated, otherwise it requires a significant amount of time and effort to accomplish manually. This won't solve anything though, since the issue with automated testing is that it can only work with what can be automated, which may only be a small subset of the engine functionality.
> 
> At the moment, I don't see any easy solution to the topic of testing, but hopefully someone else can, and this is perhaps better left to a separate discussion. For now, it is best we focus on the issue mentioned in your initial post. Have you managed to get anywhere with the CPU profiling?

Hi rh101,
    I just finished creating a minimalistic app with just 2 layers and will switch between them to check. Will keep you posted.
    
    Thank you,
    Stay safe

**Comment by asnagni** [comment] 2024-10-02 12:14
> This issue is regression introduced by 2.1.5, and 2.1.4 works fine, right?

Hi halx99,
   We jumped from 2.1.3 to 2.1.5 So I'm not sure about 2.1.4 
    But if you want we can give it a try. But the puzzling part for us, is that we don't see it on Android regardless the version.
    
    Please let me know if you want us to test on 2.1.4

**Comment by asnagni** [comment] 2024-10-02 14:14
Hi,
   Following the creation of the minimalistic test app, we were unable to reproduce the micro hangs. This suggests that the issue may lie elsewhere in the code. We are continuing to investigate and will proceed with a systematic, step-by-step approach.

Currently, we have identified that removing the LayerMultiplex  switch from in our code and clicking the buttons prevent the micro hangs. Based on this finding, we are incrementally reintroducing the removed code to isolate and identify the root cause of the issue.

I’ve attached the test files we created for evaluation, as well as a short video demonstrating the test.

Thank you very much for your patience and understanding.


https://github.com/user-attachments/assets/413d90e6-03dc-4af6-b2c9-db177645b904





[HelloCpp 2.zip](https://github.com/user-attachments/files/17230664/HelloCpp.2.zip)


Thank you,
Stay safe

**Comment by asnagni** [comment] 2024-10-02 15:50
Good news! Update: Source of Micro Delays Identified

After thoroughly isolating various code blocks, we were able to pinpoint the section responsible for the micro delays. The issue stems from the interaction with native code using the EasyNDK-for-cocos2dx framework.

Specifically, the delay occurs when switching between screens. During this process, the callbacks from the previous screen are canceled, and new ones are set for the incoming screen. It appears that setting these handlers and callbacks is introducing the micro delays.

Notably, this issue affects only iOS due to platform-specific behavior at a low level, which explains why Android is not impacted.

With the root cause identified, we will now focus on investigating potential solutions and determining how best to mitigate or resolve this issue.

Thank you for your continued patience.
Best regards,
Stay safe

**Comment by rh101** [comment] 2024-10-02 17:03
> Notably, this issue affects only iOS due to platform-specific behavior at a low level, which explains why Android is not impacted.

Are you referring to platform-specific behavior in the EasyNDK-for-cocos2dx framework, or in Axmol?

**Comment by asnagni** [comment] 2024-10-02 17:20
Hi @rh101,

To clarify, I’m referring to platform-specific behavior in the EasyNDK-for-cocos2dx framework. The implementation in EasyNDK-for-cocos2dx branches at a low level to handle platform-specific differences. My assumption is that something may have changed during the recent upgrade, which is causing this issue.

That said, after identifying the root cause, my perspective is that EasyNDK-for-cocos2dx should comply with the Axmol framework/interface, not the other way around. I'm curious if you agree with that view.

We'll be working on a solution to address this problem. After resolving it, I still plan to investigate further during my free time to understand why only iOS is impacted—purely out of curiosity.

Thank you, and stay safe.

**Comment by rh101** [comment] 2024-10-02 17:26
> That said, after identifying the root cause, my perspective is that EasyNDK-for-cocos2dx should comply with the Axmol framework/interface, not the other way around. I'm curious if you agree with that view.

Yes, that should be the case.  Given that the framework seems to have been created for Cocos2d-x, then adapting it to Axmol would be the way to go.  If it hasn't already been adapted to some degree, and just worked as-is, then that would be very surprising.  I'm curious as to what the actual issue is though, so please do update this thread when you do discover the root cause of the problem.

If you're certain that it is not a problem with Axmol, then please do not forget to close this issue.

**Comment by asnagni** [comment] 2024-10-02 17:36
Hi @rh101,

We’ll continue working on this issue today and tomorrow, and we’ll be sure to close it once we’re 100% certain it's resolved. From what I can tell, it looks like EasyNDK-for-cocos2dx needs to be updated to fully align with Axmol.

No worries, I’ll definitely share any updates and solutions as we make progress.

Thank you for your input!
Stay safe

**Comment by asnagni** [comment] 2024-10-02 21:07
Hey @rh101,
We ported the EasyNDK-for-cocos2dx library to Axmol, and everything is now working smoothly. The changes and improvements we did are minimal, but here’s a brief summary of the updates:
	
1. JSON Parsing and Selector Calls:
    ◦ We now use dispatch_async(dispatch_get_main_queue()) to ensure UI updates and selector calls occur on the correct thread.
    ◦ Improved error handling for JSON processing before selector calls.
    ◦ Direct main thread blocking is avoided by checking respondsToSelector early.
    ◦ JSON parsing (json_loads) has been moved to a background thread, preventing app hangs in case of issues (frequent large or complex parameters).
    
2. Error Handling and JSON Conversion:
    ◦ In the previous implementation, JSON deserialization errors were either logged or ignored, which could result in unexpected behavior or minor pauses. We’ve improved this by enhancing error logging and introducing retry mechanisms to handle JSON failures more gracefully.
    
[Archive.zip](https://github.com/user-attachments/files/17235983/Archive.zip)


I will close this Bug now.

Thank you,
Stay safe

**Closed as completed** 2024-10-02 21:07 UTC

**Comment by halx99** [comment] 2024-10-02 23:37
so, this issue not caused by axmol 2.1.4 or 2.1.5 changes?

**Comment by asnagni** [comment] 2024-10-03 00:17
That is correct. Axmol works fine .Sent from my iPhoneOn Oct 2, 2024, at 7:38 PM, halx99 ***@***.***> wrote:﻿
so, this issue not caused by axmol 2.1.4 or 2.1.5 changes?

**Comment by rh101** [comment] 2024-10-03 05:14
> We ported the EasyNDK-for-cocos2dx library to Axmol, and everything is now working smoothly.

Consider forking [EasyNDK-for-cocos2dx](https://github.com/aajiwani/EasyNDK-for-cocos2dx) on github to rename and add your changes to it, so others may easily find it in case they have a use for the same framework with Axmol.

**Comment by danialias** [comment] 2024-10-06 07:28
Yes, it would be great to have an Axmol fork of EasyNDK-for-cocos2dx. EasyNDK-for-Axmol maybe? Thank you!

**Comment by asnagni** [comment] 2024-10-06 10:17
Hi Guys,
   If you want to use the EasyNDK-for-cocos2dx I will suggest that you use this version here. The other one we shared contains features that are specific to our use case.
￼￼

Thank you,
Stay safe

**Comment by danialias** [comment] 2024-10-06 12:34
You mean the one in the archive.zip here? https://github.com/axmolengine/axmol/issues/2196#issuecomment-2389698128

**Comment by asnagni** [comment] 2024-10-06 12:57
Yes that one is specific to our needs. We were sharing how we were modifying it to fit our specific needs.

**Comment by asnagni** [comment] 2024-10-06 12:58
If you want something generic, use the last files that I sent you. We updated them to work with Axmol.

I hope that helps.
