### ISSUE TITLE
Update some lua code, then black screen

### ISSUE THREAD

**Issue by jie-meng** [axmolengine/axmol#1856] opened 2024-04-27 07:29 UTC
- axmol version: latest verison of 'dev' branch
- devices test on: MacBookPro M3 Max
- developing environments
   - Xcode version: 15.3
   - cmake version: 3.29.2
Steps to Reproduce:

1. git pull the latest dev branch code of axmol
2. Execute `./setup.ps1` under axmol
3. Execute `axmol new -p org.axmol.hellolua -d ~\workspace\games\ -l lua HelloLua` to create a new project
4. Execute `axmol build -p osx -a arm64 -c` to build the HelloLua project
5. Execute `axmol run`, it will build and show me the axmol hello world scene.
6. Duplicate the MainScene.lua, name the new file MainSceneX.lua, update the code in MainSceneX.lua with the new class name "MainSceneX"
7. Change the line 8 of AppBase.lua in Content/src/packages/mvc/, make it 'defaultSceneName = "MainSceneX"
8. Execute `axmol run` again, then I got black screen
9. Not only with this reproduce process, whenever I add some new lua files, tried to import them to the MainScene, I got the black screen, I can only write the code into MainScene.lua, that is the only way it take effect.

**Comment by halx99** [comment] 2024-04-27 12:55
While, on macos, the develop workflow should stupid, will build resources to HelloCpp.app, you need always regenerate cmake when you add new resources, due to it's no chance to use symlink like windows and linux.

**Comment by jie-meng** [comment] 2024-04-28 02:13
I tried to:
1. remove "build_arm64" directory
2. Execute "axmol build -p osx -a arm64 -c"
3. And then "axmol run" again, still got black screen.

**Comment by halx99** [comment] 2024-04-28 02:43
That's strange

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rh101** [comment] 2024-04-29 01:06
@jie-meng Tested this, and cannot reproduce the issue.  

Please show the contents of the `MainSceneX.lua` file, as well as the console output.  If there is an error in LUA, then it will be printed out in the console.

Just FYI, the only way I managed to get the black screen is if I purposely put an error into `MainSceneX.lua`, such as not renaming all "MainScene" to "MainSceneX" after copying `MainScene.lua` to `MainSceneX.lua`, so perhaps that would be the issue for you?

**Comment by jie-meng** [comment] 2024-04-30 06:58
I just pushed the project code to: https://github.com/jie-meng/HelloLua.
And this is MainSceneX.lua: https://github.com/jie-meng/HelloLua/blob/main/Content/src/app/views/MainSceneX.lua

<img width="1677" alt="Screenshot 2024-04-30 at 14 53 28" src="https://github.com/axmolengine/axmol/assets/7405315/9d1801af-605d-4eb4-8ddc-719c2b044fae">


<img width="1280" alt="Screenshot 2024-04-30 at 14 53 34" src="https://github.com/axmolengine/axmol/assets/7405315/6db7a4ce-6cf6-4ded-9d14-fdf82a2bba32">

**Comment by rh101** [comment] 2024-04-30 07:23
> I just pushed the project code to: https://github.com/jie-meng/HelloLua. And this is MainSceneX.lua: https://github.com/jie-meng/HelloLua/blob/main/Content/src/app/views/MainSceneX.lua

I cloned that repository, and built it for MacOS arm64, and it ran correctly.  The command used to generate the project is: `axmol build -p osx -a arm64 -c -f`, then opened the project up in Xcode and clicked the build/run command.

The only differences I can see is that you're using Darwin 23.4.0, and Xcode 15.3, whereas I'm using Darwin 22.6.0 and Xcode 15.0.1.

**Comment by jie-meng** [comment] 2024-04-30 07:46
It works when I type `axmol build -p osx -a arm64 -c -f`.

This document 
https://github.com/axmolengine/axmol/blob/dev/docs/DevSetup.md

said:
for macOS arm64(M1) axmol build -p osx -a arm64 -c

And I didn't seen any parameter instruction about "-f"
So what's the meaning of "-c" & "-f"?

**Comment by rh101** [comment] 2024-04-30 07:49
> It works when I type `axmol build -p osx -a arm64 -c -f`.

That means the project was never updated after `MainSceneX.lua` was created.  The `-f` is to force cmake to regenerate the xcode project, which is always required when new files are added.

> This document
> https://github.com/axmolengine/axmol/blob/dev/docs/DevSetup.md
> said:
> for macOS arm64(M1) axmol build -p osx -a arm64 -c

That is only for initially generating the project, but cmake does not detect changes in the Contents folder, which is where the LUA files are, so the only way to update the project is to force it with `-f`.  This should be added to the documentation.

**Comment by rh101** [comment] 2024-04-30 07:52
> So what's the meaning of "-c" & "-f"?

`-c` just generates the project files, and does not build the project
`-f` forces cmake to update the project files even if cmake does not detect changes

**Comment by rh101** [comment] 2024-04-30 08:34
@jie-meng Please close this issue if it is now resolved for you.

**Comment by jie-meng** [comment] 2024-04-30 08:35
On MacOS, there is another problem... Cannot print log.

I tried this:
```lua
local TestScene = class("TestScene", cc.load("mvc").ViewBase)

function TestScene:onCreate()
    -- add background image
    display.newSprite("HelloWorld.png")
        :move(display.center)
        :addTo(self)

    -- add HelloWorld label
    cc.Label:createWithSystemFont("Test", "Arial", 40)
        :move(display.cx, display.cy + 200)
        :addTo(self)

    printLog("TestScene", "TestLog")
end

return TestScene
```


The "printLog" in functions.lua uses standard lua function "print", I don't know if it has bridged to MacOS app standard terminal output or not.
Nothing printed.

**Closed as completed** 2024-04-30 08:36 UTC
Labels: need-info
