### ISSUE TITLE
Error (with fix): OpenAL having compilation issues.

### ISSUE THREAD

**Issue by TheNachoBIT** [axmolengine/axmol#1144] opened 2023-03-29 22:34 UTC
Axmol Version: Release
__________________________________
Hello! I had this issue where the OpenAL build finds the OSS, but its the Clang version of it, and MSVC doesn't have such thing as OSS.

I reported this issue in here along with a solution, where i go in much more detail (also saying that the error was discovered & fixed in Axmol Engine): https://github.com/kcat/openal-soft/issues/839

I'm not sending any PRs because this is probably a duck-tape solution, and also this project probably has a heavily modified version of OpenAL, but this issue happens on both Axmol's OpenAL and the OG OpenAL, both fixed with the same solution.

Hope this helps :)

**Comment by rh101** [comment] 2023-03-30 10:12
I can't reproduce this issue. MSYS2/Clang are installed on my system, and not once has there been a problem with MSVC detecting OSS or any other strange issues like that.  Are you sure this isn't something specific to your setup (such as environment paths etc.)?

**Comment by rh101** [comment] 2023-04-28 11:34
This issue was apparently addressed in this commit:  https://github.com/kcat/openal-soft/commit/3e4a2a151860c04fb0ebb971343a6f05e0c3c08a

**Comment by halx99** [comment] 2023-05-03 11:04
should fixed by https://github.com/axmolengine/axmol/commit/dfa87703ca707b9b6a7d11e83310dcac42d5d9a9

**Closed by halx99** 2023-05-03 11:04 UTC
Labels: help wanted
