### ISSUE TITLE
Shader files not found when building with cmake 

### ISSUE THREAD

**Issue by Papirosnik** [axmolengine/axmol#1833] opened 2024-04-18 08:54 UTC
- axmol version: 2.1.2
- devices test on: mac m1
- developing environments
   - NDK version: r23c
   - Xcode version: 15.3
   - Visual Studio Code: 1.88.1
   - cmake version: 3.29.1
Steps to Reproduce:

1. Create new project:
   axmol new -p com.mycomp.test1 -d ./ -l cpp --portrait test1
2. Open it in VSCode (having all the necessary c++/cmake extension installed)
3. Build project (F7) - Suceess
4. Launch it - app crashes at start
<img width="1140" alt="image" src="https://github.com/axmolengine/axmol/assets/1651549/698ecf1b-6321-4360-8c26-b8efe4084756">
5. Go to terminal and re-build the project from there using axmol command:
    axmol build -p osx -a arm64     
6. Sucess - and the app launches now without any crashes!
<img width="719" alt="image" src="https://github.com/axmolengine/axmol/assets/1651549/90cbc980-8ff1-45a7-9660-3b81a9ff5e9d">

What's wrong with cmake build?

**Comment by Papirosnik** [comment] 2024-04-18 08:59
Oh, I see the difference - cmake from VSCode is builduing the project into my 'custom' extension build folder - namely _.build_
While the ouput folder for axmol build command is 'build_arm64'.

**Comment by rh101** [comment] 2024-04-18 09:20
This is not a bug in Axmol, and most likely a configuration issue in your VSCode environment.

Can you configure VSCode to use `axmol build -p osx -a arm64`? Add `-c` if all you want it to do is to generate the project files, but not build.

Also, if you want to see the entire cmake command that is being generated when the `axmol build` script is run, then check PR https://github.com/axmolengine/axmol/pull/1834 to see what modification you can make in order to see that information.  You can then just configure VSCode to use that same cmake command that you see printed in the console.

Please close this issue, unless you do believe there is some kind of bug in Axmol.

**Closed as completed** 2024-04-18 12:11 UTC
