### ISSUE TITLE
HelloLua/lua_tests build arm64 osx app does not launch 

### ISSUE THREAD

**Issue by xu-yuan** [axmolengine/axmol#1303] opened 2023-08-23 07:42 UTC
- axmol version: 1.x
- devices test on: Mac Studio Apple M2 Max 
- developing environments
   - Xcode version: 14.3.1
   - cmake version: 3.27.1
Steps to Reproduce:

1. Create project with `pwsh build.ps1 -p osx -a arm64`
2. The project can compile successfully but fail to run
3. The following error message appears

Details

Could not launch “HelloLua”
Domain: IDELaunchErrorDomain
Code: 20
Recovery Suggestion: The LaunchServices launcher has returned an error. Please check the system logs for the underlying cause of the error.
User Info: {
    DVTErrorCreationDateKey = "2023-08-23 07:30:06 +0000";
    DVTRadarComponentKey = 968756;
    IDERunOperationFailingWorker = IDELaunchServicesLauncher;
}
--
The operation couldn’t be completed. Launch failed.
Domain: RBSRequestErrorDomain
Code: 5
Failure Reason: Launch failed.
--
Launchd job spawn failed
Domain: NSPOSIXErrorDomain
Code: 153
--

Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "Mac14,13";
    "device_osBuild" = "13.5.1 (22G90)";
    "device_platform" = "com.apple.platform.macosx";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 34;
    "operation_errorCode" = 20;
    "operation_errorDomain" = IDELaunchErrorDomain;
    "operation_errorWorker" = IDELaunchServicesLauncher;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.macosx";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "macosx13.3";
    "sdk_osVersion" = "13.3";
    "sdk_variant" = macos;
}
--

System Information

macOS Version 13.5.1 (Build 22G90)
Xcode 14.3.1 (21815) (Build 14E300c)
Timestamp: 2023-08-23T15:30:06+08:00

**Comment by halx99** [comment] 2023-08-23 09:22
Try add follow config into mac info.plist
```
<key>LSMinimumSystemVersion</key>
<string>${MACOSX_DEPLOYMENT_TARGET}</string>
```

**Comment by xu-yuan** [comment] 2023-08-23 13:20
> Try add follow config into mac info.plist
> 
> ```
> <key>LSMinimumSystemVersion</key>
> <string>${MACOSX_DEPLOYMENT_TARGET}</string>
> ```

I tried, but it didn't work

**Comment by halx99** [comment] 2023-08-23 13:39
Does the HelloCpp works?

**Comment by xu-yuan** [comment] 2023-08-23 16:24
HelloCpp/cpp_tests can works, but lua projects can not works.

**Comment by halx99** [comment] 2023-08-26 14:28
I can't reproduce on my intel macOS latest, could you use beyondcompare to compare HellpCpp & HelloLua to fire which different  cause the issue?

**Comment by rh101** [comment] 2023-09-26 07:53
@halx99 Can confirm that the lua test project (branch 1.0) builds correctly, but fails to load (on Mac M1 Mini with MacOS 13.4.1):

```
Could not launch “lua_tests”
Domain: IDELaunchErrorDomain
Code: 20
Recovery Suggestion: The LaunchServices launcher has returned an error. Please check the system logs for the underlying cause of the error.
User Info: {
    DVTErrorCreationDateKey = "2023-09-26 07:49:42 +0000";
    DVTRadarComponentKey = 968756;
    IDERunOperationFailingWorker = IDELaunchServicesLauncher;
}
--
The operation couldn’t be completed. Launch failed.
Domain: RBSRequestErrorDomain
Code: 5
Failure Reason: Launch failed.
--
Launchd job spawn failed
Domain: NSPOSIXErrorDomain
Code: 153
--
```

Build using the command line and also from within Xcode, and the same error appears when attempting to launch it.  The cpp-tests project build and runs without problems.

**Comment by halx99** [comment] 2023-09-26 08:07
Can you fire the reason, compare project HelloLua with HelloCpp by beyondcomare?

**Comment by rh101** [comment] 2023-09-26 09:13
> Can you fire the reason, compare project HelloLua with HelloCpp by beyondcomare?

Will do.

**Comment by rh101** [comment] 2023-09-26 10:01
@halx99 The linker was complaining about this:

```
ld: warning: Linking with PIE, -image_base will be ignored
ld: warning: non-standard -pagezero_size is deprecated when targeting macOS 13.0 or later
```
So, I commented this out from `CMakeLists.txt`:

        set_target_properties(${APP_NAME} PROPERTIES
            LINK_FLAGS "-pagezero_size 10000 -image_base 100000000"
        )

With that change and a rebuild, the lua_project ran (within Xcode so I could debug), and it crashed because `glView` is NULL in here:

```

int Application::run()
{
    initGLContextAttrs();
    if (!applicationDidFinishLaunching())
    {
        return 1;
    }

    std::chrono::steady_clock::time_point lastTime{};

    constexpr std::chrono::nanoseconds _1ms{1000000};

    auto director = Director::getInstance();
    auto glView   = director->getOpenGLView();

    // Retain glView to avoid glView being released in the while loop
    glView->retain(); <== **** crashes here ****
```

In the console output I see this:
```
axmol: fullPathForFilename: No file found at axmol/init.lua. Possible missing file.
axmol: fullPathForFilename: No file found at axmol/init/init.lua. Possible missing file.
can not get file data of axmol/init/init.lua
[LUA ERROR] controller.lua:13: module 'axmol.init' not found:
	no field package.preload['axmol.init']
	no file '/usr/local/share/lua/5.4/axmol/init.lua'
	no file '/usr/local/share/lua/5.4/axmol/init/init.lua'
	no file '/usr/local/lib/lua/5.4/axmol/init.lua'
	no file '/usr/local/lib/lua/5.4/axmol/init/init.lua'
	no file './axmol/init.lua'
	no file './axmol/init/init.lua'
	no file '/usr/local/lib/lua/5.4/axmol/init.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './axmol/init.so'
	no file '/usr/local/lib/lua/5.4/axmol.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './axmol.so'
(lldb) 
```
The files inside the "Resources/Contents" folder of lua_tests.app are:
```
AccelerometerTest
ActionManagerTest
ActionsEaseTest
ActionsProgressTest
ActionsTest
AssetsManagerExTest
AssetsManagerTest
BillBoardTest
BugsTest
Camera3DTest
CaptureScreenTest
ClickAndMoveTest
ComponentTest
CurrentLanguageTest
DownloaderTest
DrawPrimitivesTest
EffectsAdvancedTest
EffectsTest
ExtensionTest
FastTiledMapTest
FileUtilsTest
FontTest
IntervalTest
KeypadTest
LabelTestNew
LayerTest
LightTest
LuaBridgeTest
LuaLoaderTest
MaterialSystemTest
MenuTest
MotionStreakTest
NavMeshTest
NewAudioEngineTest
NewEventDispatcherTest
NodeTest
OpenGLTest
ParallaxTest
Particle3DTest
ParticleTest
Physics3DTest
PhysicsTest
RenderTextureTest
RotateWorldTest
Scene3DTest
SceneTest
SpineTest
Sprite3DTest
SpritePolygonTest
SpriteTest
TerrainTest
TextInputTest
Texture2dTest
TileMapTest
TouchesTest
TransitionsTest
UserDefaultTest
VibrateTest
VideoPlayerTest
VisibleRect.lua
WebViewTest
XMLHttpRequestTest
ZwoptexTest
controller.lua
helper.lua
mainMenu.lua
testResource.lua
```

Does that help at all?

Also, do you want me to compare the Xcode generated project, or are you referring to the cpp_tests vs lua_tests folder comparison?

**Comment by halx99** [comment] 2023-09-26 10:14
No require, the root cause should be
```cmake
set_target_properties(${APP_NAME} PROPERTIES
        LINK_FLAGS "-pagezero_size 10000 -image_base 100000000"
    )
```
seems: the lua-tests missing engine script folder `axmol`
Does the HelloLua works ?

**Comment by halx99** [comment] 2023-09-26 10:19
@rh101 Would you like make a PR?

**Comment by rh101** [comment] 2023-09-26 10:26
> @rh101 Would you like make a PR?

Sure, I'll create one soon.  Also testing out a new HelloLua project to make sure it works.

**Comment by halx99** [comment] 2023-09-26 10:32
confirmed: the HelloLua should works, the `lua_tests` missing res folder in `Contents/Resources`

**Comment by rh101** [comment] 2023-09-26 10:34
> confirmed: the HelloLua should works, the `lua_tests` missing res folder in `Contents/Resources`

Yep, just tested it too and it works fine.

**Comment by halx99** [comment] 2023-09-26 12:06
> > confirmed: the HelloLua should works, the `lua_tests` missing res folder in `Contents/Resources`
> 
> Yep, just tested it too and it works fine.

tks, merged, will sync to dev soon

**Closed as completed** 2023-09-26 12:06 UTC
Labels: bug
